apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-pvc
spec:
  storageClassName: "ebs-sc" # Empty string must be explicitly set otherwise default StorageClass will be set
  # PV Name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 75Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic-pod
  labels:
    purpose: "ebs-dynamic"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: ebs-dynamic-lb
spec:
  type: LoadBalancer
  selector:
    purpose: "ebs-dynamic"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30660