apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: efs-static-pv
  resources:
    requests:
      storage: 45Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static-pod
  labels:
    purpose: "efs-static"
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static-pvc

---

kind: Service
apiVersion: v1
metadata:
  name: efs-static-lb
spec:
  type: LoadBalancer
  selector:
    purpose: "efs-static"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30659