apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: efs-static-pv
  resources:
    requests:
      storage: 45Gi