apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: expense
  labels:
    environment: production
    project: expense
    component: backend
spec:
  containers:
    - name: nginx
      image: nginx