apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    buildURL: "http://ci.example.com/job/1234/"
    imageregistry: "dockerhub.io/nginx"
spec:
  containers:
    - name: nginx
      image: nginx