apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        #soft limits
        requests:
          memory: "64Mi"
          cpu: "250m"
        #hard limits
        limits:
          memory: "128Mi"
          cpu: "500m"