kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    project: expense
    component: backend
    environment: production
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    environment: production
    project: expense
    component: backend
    version: v1
spec:
  containers:
    - name: nginx
      image: nginx