kind: Service
apiVersion: v1
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    project: expense
    component: backend
    environment: production
    version: v1
    demo: np
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-np
  labels:
    project: expense
    component: backend
    environment: production
    version: v1
    demo: np
spec:
  containers:
    - name: nginx
      image: nginx
      
