kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    project: expense
    component: backend
    environment: production
    version: v1
    demo: lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      NodePort: 30080
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-lb
  labels:
    project: expense
    component: backend
    environment: production
    version: v1
    demo: lb
spec:
  containers:
    - name: nginx
      image: nginx
      
