apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # these are replicaset labels
  labels:
    app: frontend
    tier: web
    purpose: deployment
spec:
  replicas: 3
  selector:
  #replicaset use those labels to identify its pods
    matchLabels:
      app: frontend
      tier: web
      purpose: deployment
  #pod template
  template:
    metadata:
      # these are pod labels
      labels:
        app: frontend
        tier: web
        purpose: deployment
    spec:
      containers:
        - name: nginx
          image: devsecopswithaws/deployment:1.0.0
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector: #labels used as selectors
    app: frontend
    tier: web
    purpose: deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080